---
glowroot_url: "https://github.com/glowroot/glowroot/releases/download/v{{ glowroot_version }}/glowroot-central-{{ glowroot_version }}-dist.zip"

glowroot_install_dir: '/opt'
glowroot_home_dir: "{{ glowroot_install_dir }}/glowroot-central"
glowroot_owner: 'root'
glowroot_group: 'glowroot'

glowroot_port: 4000
glowroot_bind_address: '0.0.0.0'
glowroot_context_path: '/'

# Storage - data.h2.db
# Response time and JVM gauge data
glowroot_rtjg_1m: 72
glowroot_rtjg_5m: 336
glowroot_rtjg_30m: 2160
glowroot_rtjg_4h: 2160

glowroot_trace_data: 336
glowroot_full_query_text: 336

# Storage - *.capped.db
# Query, service call and profile data
glowroot_qscp_1m: 500
glowroot_qscp_5m: 500
glowroot_qscp_30m: 500
glowroot_qscp_4h: 500

glowroot_trace_detail_data: 500