---
- name: Ensure old files are not still there.
  file:
    path: "{{ glowroot_home_dir }}/{{ item }}"
    state: absent
  with_items:
    - 'glowroot-central.jar'
    - 'lib'

- name: Ensure compressed file is downloaded.
  get_url:
    url: "{{ glowroot_url }}"
    dest: "{{ glowroot_install_dir }}/glowroot.zip"

- name: Ensure downloaded file is uncompressed.
  unarchive:
    src: "{{ glowroot_install_dir }}/glowroot.zip"
    dest: "{{ glowroot_install_dir }}"
    copy: no
    creates: "{{ glowroot_home_dir }}/glowroot-central.jar"

- name: Ensure dowloaded file is removed.
  file:
    path: "{{ glowroot_install_dir }}/glowroot.zip"
    state: absent